services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./linkding/data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - homelab-network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - $HOME/data/movies/:/data/movies
      - $HOME/data/shows/:/data/shows
      - $HOME/data/youtube:/data/youtube
      - $HOME/data/music:/data/music

    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      - homelab-network

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - $HOME/data/youtube:/downloads
    networks:
      - homelab-network

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80"  # Changed to 8082
    environment:
      - TZ=Europe/Helsinki
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - homelab-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9091:9090"
    networks:
      - homelab-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - homelab-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/data:/var/lib/grafana
    networks:
      - homelab-network
    restart: unless-stopped

  dynacat:
    image: panonim/dynacat
    restart: unless-stopped
    volumes:
     - ./dynacat/config:/app/config
    ports:
     - 8080:8080
    networks:
      - homelab-network

networks:
  homelab-network:
    name: homelab-network
