services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./linkding/data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.50.0.3


  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_FILE_UPLOAD=10
    - HBOX_DATABASE_DRIVER=sqlite3
    volumes:
      - ./homebox/data:/data/
    ports:
      - 3100:7745
    networks:
      homelab-network:
        ipv4_address: 172.50.0.4

  ngix-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      homelab-network:
        ipv4_address: 172.50.0.6


    volumes:
      - ./nginxproxy/data:/data
      - ./nginxproxy/letsencrypt:/etc/letsencrypt

networks:
  homelab-network:
    name: homelab-network 
    ipam:
      config:
        - subnet: 172.50.0.0/24

