services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./linkding/data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.50.0.3

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - $HOME/data/movies/:/data/movies
      - $HOME/data/shows/:/data/shows
      - $HOME/data/youtube:/data/youtube
    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      homelab-network:
        ipv4_address: 172.50.0.4

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - $HOME/data/youtube:/downloads
    networks:
      homelab-network:
        ipv4_address: 172.50.0.5

  ngix-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      homelab-network:
        ipv4_address: 172.50.0.6

    volumes:
      - ./nginxproxy/data:/data
      - ./nginxproxy/letsencrypt:/etc/letsencrypt

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9091:9090"
    networks:
      homelab-network:
        ipv4_address: 172.50.0.7
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      homelab-network:
        ipv4_address: 172.50.0.8
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/data:/var/lib/grafana
    networks:
      homelab-network:
        ipv4_address: 172.50.0.9
    restart: unless-stopped

networks:
  homelab-network:
    name: homelab-network 
    ipam:
      config:
        - subnet: 172.50.0.0/24

