services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-./linkding/data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      homelab-network:
        ipv4_address: 172.50.0.3

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./jellyfin/config:/config
      - $HOME/data/movies/:/data/movies
      - $HOME/data/shows/:/data/shows
      - $HOME/data/youtube:/data/youtube
    ports:
      - 8096:8096
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      homelab-network:
        ipv4_address: 172.50.0.4

  ngix-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      homelab-network:
        ipv4_address: 172.50.0.6


    volumes:
      - ./nginxproxy/data:/data
      - ./nginxproxy/letsencrypt:/etc/letsencrypt

networks:
  homelab-network:
    name: homelab-network 
    ipam:
      config:
        - subnet: 172.50.0.0/24

